// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: building.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Building struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BuildingName   string  `protobuf:"bytes,1,opt,name=building_name,json=buildingName,proto3" json:"building_name,omitempty"`
	BuildingNumber uint32  `protobuf:"varint,2,opt,name=building_number,json=buildingNumber,proto3" json:"building_number,omitempty"`
	Street         *Street `protobuf:"bytes,3,opt,name=street,proto3" json:"street,omitempty"`
}

func (x *Building) Reset() {
	*x = Building{}
	if protoimpl.UnsafeEnabled {
		mi := &file_building_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Building) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Building) ProtoMessage() {}

func (x *Building) ProtoReflect() protoreflect.Message {
	mi := &file_building_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Building.ProtoReflect.Descriptor instead.
func (*Building) Descriptor() ([]byte, []int) {
	return file_building_proto_rawDescGZIP(), []int{0}
}

func (x *Building) GetBuildingName() string {
	if x != nil {
		return x.BuildingName
	}
	return ""
}

func (x *Building) GetBuildingNumber() uint32 {
	if x != nil {
		return x.BuildingNumber
	}
	return 0
}

func (x *Building) GetStreet() *Street {
	if x != nil {
		return x.Street
	}
	return nil
}

var File_building_proto protoreflect.FileDescriptor

var file_building_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x1a, 0x0c, 0x73, 0x74, 0x72, 0x65,
	0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x80, 0x01, 0x0a, 0x08, 0x42, 0x75, 0x69,
	0x6c, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x23, 0x0a, 0x0d, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e,
	0x67, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x62, 0x75,
	0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x62, 0x75,
	0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0e, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x26, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x65, 0x65, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x65, 0x74, 0x2e, 0x53, 0x74, 0x72,
	0x65, 0x65, 0x74, 0x52, 0x06, 0x73, 0x74, 0x72, 0x65, 0x65, 0x74, 0x42, 0x05, 0x5a, 0x03, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_building_proto_rawDescOnce sync.Once
	file_building_proto_rawDescData = file_building_proto_rawDesc
)

func file_building_proto_rawDescGZIP() []byte {
	file_building_proto_rawDescOnce.Do(func() {
		file_building_proto_rawDescData = protoimpl.X.CompressGZIP(file_building_proto_rawDescData)
	})
	return file_building_proto_rawDescData
}

var file_building_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_building_proto_goTypes = []interface{}{
	(*Building)(nil), // 0: building.Building
	(*Street)(nil),   // 1: street.Street
}
var file_building_proto_depIdxs = []int32{
	1, // 0: building.Building.street:type_name -> street.Street
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_building_proto_init() }
func file_building_proto_init() {
	if File_building_proto != nil {
		return
	}
	file_street_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_building_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Building); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_building_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_building_proto_goTypes,
		DependencyIndexes: file_building_proto_depIdxs,
		MessageInfos:      file_building_proto_msgTypes,
	}.Build()
	File_building_proto = out.File
	file_building_proto_rawDesc = nil
	file_building_proto_goTypes = nil
	file_building_proto_depIdxs = nil
}
